/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const camelize: typeof import('vue')['camelize']
  const computed: typeof import('vue')['computed']
  const defineStore: typeof import('pinia')['defineStore']
  const h: typeof import('vue')['h']
  const mergeProps: typeof import('vue')['mergeProps']
  const nextTick: typeof import('vue')['nextTick']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
  const onBeforeRouteUpdate: typeof import('vue-router')['onBeforeRouteUpdate']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onMounted: typeof import('vue')['onMounted']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const ref: typeof import('vue')['ref']
  const shallowRef: typeof import('vue')['shallowRef']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  const useAttrs: typeof import('vue')['useAttrs']
  const useDate: typeof import('vuetify')['useDate']
  const useDisplay: typeof import('vuetify')['useDisplay']
  const useGoTo: typeof import('vuetify')['useGoTo']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useRtl: typeof import('vuetify')['useRtl']
  const useTheme: typeof import('vuetify')['useTheme']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly camelize: UnwrapRef<typeof import('vue')['camelize']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly mergeProps: UnwrapRef<typeof import('vue')['mergeProps']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useDate: UnwrapRef<typeof import('vuetify')['useDate']>
    readonly useDisplay: UnwrapRef<typeof import('vuetify')['useDisplay']>
    readonly useGoTo: UnwrapRef<typeof import('vuetify')['useGoTo']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useRtl: UnwrapRef<typeof import('vuetify')['useRtl']>
    readonly useTheme: UnwrapRef<typeof import('vuetify')['useTheme']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
  }
}
declare module '@vue/runtime-core' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly camelize: UnwrapRef<typeof import('vue')['camelize']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly mergeProps: UnwrapRef<typeof import('vue')['mergeProps']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useDate: UnwrapRef<typeof import('vuetify')['useDate']>
    readonly useDisplay: UnwrapRef<typeof import('vuetify')['useDisplay']>
    readonly useGoTo: UnwrapRef<typeof import('vuetify')['useGoTo']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useRtl: UnwrapRef<typeof import('vuetify')['useRtl']>
    readonly useTheme: UnwrapRef<typeof import('vuetify')['useTheme']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
  }
}
