/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBackBtn: typeof import('./src/components/app/BackBtn.vue')['default']
    AppBarBar: typeof import('./src/components/app/bar/Bar.vue')['default']
    AppBarLogo: typeof import('./src/components/app/bar/Logo.vue')['default']
    AppBarNotificationsMenu: typeof import('./src/components/app/bar/NotificationsMenu.vue')['default']
    AppBarSearchDialog: typeof import('./src/components/app/bar/SearchDialog.vue')['default']
    AppBarThemeToggleBtn: typeof import('./src/components/app/bar/ThemeToggleBtn.vue')['default']
    AppBarUserMenu: typeof import('./src/components/app/bar/UserMenu.vue')['default']
    AppBreadcrumb: typeof import('./src/components/app/Breadcrumb.vue')['default']
    AppConfirmDialog: typeof import('./src/components/app/ConfirmDialog.vue')['default']
    AppDataTable: typeof import('./src/components/app/DataTable.vue')['default']
    AppDatePicker: typeof import('./src/components/app/DatePicker.vue')['default']
    AppDrawerAppend: typeof import('./src/components/app/drawer/Append.vue')['default']
    AppDrawerDrawer: typeof import('./src/components/app/drawer/Drawer.vue')['default']
    AppDrawerList: typeof import('./src/components/app/drawer/List.vue')['default']
    AppDrawerPrepend: typeof import('./src/components/app/drawer/Prepend.vue')['default']
    AppLabel: typeof import('./src/components/app/Label.vue')['default']
    AppSnackBarQueue: typeof import('./src/components/app/SnackBarQueue.vue')['default']
    AuthLoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    OrderBasicInfoSection: typeof import('./src/components/order/BasicInfoSection.vue')['default']
    OrderBillSection: typeof import('./src/components/order/BillSection.vue')['default']
    OrderDataTable: typeof import('./src/components/order/DataTable.vue')['default']
    OrderItemsSection: typeof import('./src/components/order/ItemsSection.vue')['default']
    OrderMoreMenu: typeof import('./src/components/order/MoreMenu.vue')['default']
    OrderNoteSection: typeof import('./src/components/order/NoteSection.vue')['default']
    OrderPriceSection: typeof import('./src/components/order/PriceSection.vue')['default']
    OrderStatusChip: typeof import('./src/components/order/StatusChip.vue')['default']
    OrderStatusFilterMenu: typeof import('./src/components/order/StatusFilterMenu.vue')['default']
    OrderStatusStepper: typeof import('./src/components/order/StatusStepper.vue')['default']
    PayWechatConfig: typeof import('./src/components/pay/wechatConfig.vue')['default']
    ProductDataTable: typeof import('./src/components/product/DataTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingBasicAlipayMiniDialog: typeof import('./src/components/setting/basic/AlipayMiniDialog.vue')['default']
    SettingBasicAppConfig: typeof import('./src/components/setting/basic/AppConfig.vue')['default']
    SettingBasicProfile: typeof import('./src/components/setting/basic/Profile.vue')['default']
    SettingBasicWechatMiniDialog: typeof import('./src/components/setting/basic/WechatMiniDialog.vue')['default']
    SettingPayAddDialog: typeof import('./src/components/setting/pay/AddDialog.vue')['default']
    SettingPayAlipayForm: typeof import('./src/components/setting/pay/AlipayForm.vue')['default']
    SettingPayWechatConfig: typeof import('./src/components/setting/pay/WechatConfig.vue')['default']
    SettingPayWechatForm: typeof import('./src/components/setting/pay/WechatForm.vue')['default']
    SettingTabs: typeof import('./src/components/setting/Tabs.vue')['default']
    StockDataTableHeader: typeof import('./src/components/stock/DataTableHeader.vue')['default']
  }
}
