name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.1'

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build

    - name: Archive dist directory
      uses: actions/upload-artifact@v2
      with:
        name: dist.tar
        path: dist

    - name: List file
      run: ls -l
    - name: Copy files via SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: 'root'
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "dist.tar"
        target: "/home/app/admin-ui"
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: 'root'
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/app/admin-ui
          rm -rf dist
          tar xvf dist.tar
