name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.1'

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build

    - name: Archive dist directory
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Copy dist.tar to server
        run: scp -P 22 -f $GITHUB_WORKSPACE/dist.tar root@${{ secrets.SERVER_HOST }}:/home/app/admin-ui/
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: 'root'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/app/admin-ui
            rm -rf dist
            tar xvf dist.tar
